image: naskpl/docker-compose

variables:
  DOCKER_DRIVER: overlay2

services:
  - naskpl/dind

stages:
  - build
  - test

before_script:
  - echo "Start job $CI_BUILD_NAME" at `date +%Y-%m-%d-%H-%M-%S`
  - echo "CI_PIPELINE_ID $CI_PIPELINE_ID"
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"

build_ursadb:
  stage: build
  script:
    - docker build -t "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" .
    - docker tag "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" "$DOCKER_REGISTRY/ursadb:latest"

    - docker push "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID"
    - docker push "$DOCKER_REGISTRY/ursadb:latest"

test_ursadb:
  stage: test
  script:
    - docker pull "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" > /dev/null
    - docker run --entrypoint "/usr/bin/ursadb_test" "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID"
