image: certpl/docker-ci-base:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - naskpl/dind

stages:
  - build
  - deploy

before_script:
  - echo "Start job $CI_BUILD_NAME" at `date +%Y-%m-%d-%H-%M-%S`
  - echo "CI_PIPELINE_ID $CI_PIPELINE_ID"
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"

build_ursadb:
  stage: build
  script:
    - docker build -t "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" .
    - docker tag "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" "$DOCKER_REGISTRY/ursadb:latest"
    - docker tag "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID" "$DOCKER_REGISTRY/ursadb:build-$CI_COMMIT_SHA"

    - docker push "$DOCKER_REGISTRY/ursadb:$CI_PIPELINE_ID"
    - docker push "$DOCKER_REGISTRY/ursadb:build-$CI_COMMIT_SHA"
    - docker push "$DOCKER_REGISTRY/ursadb:latest"

deploy_ursadb:
  stage: deploy
  when: manual
  only:
    - master
  environment:
    name: prod
  script:
    - eval $(ssh-agent -s)
    - echo "$GIT_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$VCS_SSH_KEYS" >> ~/.ssh/known_hosts
    - git clone "$VCS_DEPLOY_REPO_URL"
    - cd "$VCS_DEPLOY_REPO_NAME"
    - sh deploy_ursadb.sh
